### PR TITLE
change the dock icon of the app.

### LINKED ISSUE #240: Change dock icon of OS X app.
**Branch** develop

**Target** 0.16.x

**Current Behaviour** The dock icon is very small and not readable.

**Expected Behaviour** The dock icon can use the KA-Lite icon (the green leaf icon, same as Khan Academy's?)

This is related to #114 

Here's the problematic dock icon:

ka-lite-monitor-dock-icon-2015-10-27a

### PR DESCRIPTION
**Pull request by amodia**
@cpauya & @aronasorman  this fixes #240 

I attached sample screenshot.
screen shot 2015-10-28 at 2 53 38 pm

### CODE REVIEW

**Comment by djallado** [comment]
@amodia, I tested your PR and look like the image is pixelated.
Here's my snapshot:
scrka-lite

**Comment by cpauya** [comment]
@amodia Merge conflicts.

**Comment by cpauya** [comment]
@amodia I just shared (view-only) the FLE Design -> Logos folder for you on Google Drive... there should be some logos for your needs. :smile_cat:

**Comment by amodia** [comment]
@cpauya I'm done updating the dock icon, here's the sample screenshot.
screen shot 2015-10-29 at 11 47 28 am

**Comment by djallado** [comment]
Nice. @amodia.
Here' my snapshot:
scrlogo

**Comment by cpauya** [comment]
Looks good, merging.

**Pull request merged**
