### PR TITLE
Debian build script for docker

### LINKED ISSUE #396: Debian Build Script for KA-Lite Installer
## Summary

**Problem**

- There is no build script to automate the process to create the *.deb files.

**Objectives**   
- To create a debian build script that automate the docker image to produce *.deb files.
- Create a signed deb file.
- Run the build script in the bamboo server.

## Branch or installer

 - Installer: `Debian`
 - Branch: `master`

### PR DESCRIPTION
**Pull request by arceduardvincent**
## Summary
- Fixes #396
- To create a debian build script that automate the docker image to produce *.deb files.
- Create a signed deb file
- Run the build script in the bamboo server.

## TODO

- [x] Check if docker is installed.
- [x] Build the docker image.
- [x] Create a docker build tag.
- [x] Run `docker-entrypoint.sh` script in the docker image.
- [x] Display the newly built deb files in the `~/installers/debian/docker/temp/installers` directory.
- [ ] Update the `README.md`.

**Building the static sources of the ka-lite repo**
- [x] Building the static sources for develop branch of the ka-lite repo with python setup.py sdist --static and  then extracting to `working_dir`
- [x] Moving the `debian/debian` sources inside the root of the unpacked ka-lite/ sdist.
- [x] Install build requirements `sudo apt-get install equivs gdeb`i + `mk-build-deps --remove --install <controfile>`
- [x] Run `debuild -b -us -uc` at the root of the unpacked `ka-lite/` sdist
- [x] Create a signed deb file.
- [ ] Create a signed deb file.

**Building the static sources for PPA**
- [x] Create deb files
- [ ] Create a signed deb file.

## Reviewer guidance
We are trying to automate the production of the *.deb files and signed it.
How to use the build script?
- Navigate to the `~/installers/debian/docker`
- Run `./build.sh`
- Once the script is done, you should see some output like this
```
Congratulations! Your newly built installer is at '/Users/arceduardvincent/installers/debian/docker/temp/installers'.
ka-lite-bundle_0.16.6-0ubuntu1_all.deb	      ka-lite_0.16.6-0ubuntu1_all.deb
ka-lite-raspberry-pi_0.16.6-0ubuntu1_all.deb
Done!
```
## Screenshots
I install the new built deb file in ubuntu 16.04. See image attach

ka-lite-bundle_0.16.6-0ubuntu1_all.deb size=294mb
screen shot 2016-05-13 at 5 24 18 pm

ka-lite_0.16.6-0ubuntu1_all.deb size=35.7
screen shot 2016-05-13 at 6 27 49 pm

### CODE REVIEW

**Comment by benjaoming** [comment]
@arceduardvincent nice work, great Bash scripting :)

Please ping me about review stuff for the debian building once you have it in place -- looking forwards to this improvement!

Btw. regarding branches and Bamboo setup.. all builds should use the `debian/debian/` source folder for the branch which is being build. Just saying this in case you have had plans to use a static copy or download a source package from the PPA.. ideally, the repo's `debian/` folder is the source, but it also changes frequently.

For instance, building a new KA Lite with the latest source from `develop` should be a matter of:

(I take it this is run inside the docker container...)

1) Building the static sources for `develop` branch of the `ka-lite` repo with `python setup.py sdist --static` and then extracting to some folder

2) Moving the `debian/debian` sources inside the root of the unpacked `ka-lite/` sdist.

3) Install build requirements `sudo apt-get install equivs gedbi` + `mk-build-deps --remove --install <controfile>` - this will install the build dependencies directly using the debian source's `control` file.

4) Run `debuild -b -us -uc` at the root of the unpacked `ka-lite/` sdist (but we should probably build something signed though). Notice the `-b`, we should be able to skip building a source package and just do the binaries.

I didn't test the above, it's a draft, but I hope it'll be helpful :)

**Comment by arceduardvincent** [comment]
Hello @benjaoming thanks for the appreciation and suggestion.
The new improvement of this script will focus on the draft you suggested that this script will be compatible with branches and Bamboo setup. 
I will update the checklist and the trello for this changes.

I will update you once I'm done with the changes.
thanks

**Comment by benjaoming** [comment]
@arceduardvincent - am so excited about this, how's it going and do you need any feedback at this point?

**Comment by cpauya** [comment]
Just a note that [this is the Trello card](https://trello.com/c/CIfUvrYB/196-build-debian-package-for-ka-lite) that @arceduardvincent said above.

@benjaoming I think one of the missing parts left here is code-signing?  Any ideas/suggestions on how to do that for the debian builds?

**Comment by benjaoming** [comment]
@cpauya we have an email address kalitebuilder@learningequality.org and I have PGP keys for it, that might be useful, as long as they don't end up in a public repo :)

It even has a PPA account and so with a simple command it could upload to our ka-lite-proposed PPA, but I suggest we only do that as a manual addition since we don't wanna overload Launchpad's services.

**Comment by cpauya** [comment]
Got it @benjaoming, let's do the code-signing and uploading manually.

For the current status: I remember him saying this PR already builds 3 .deb files in the docker container and he was trying to copy those in the host computer (example: for moving to Pantry).  Please validate if I'm correct @arceduardvincent.

After that, then I think the last thing for this is the "Run the build script in the bamboo server." task.

**Comment by benjaoming** [comment]
@cpauya do you know where the builds retrieve their assessment.zip from? Latest from pantry?

Moving stuff to pantry can remain a manual procedure -- the main achievement here is being able to serve the latest build for community doing tests to verify that their issues are fixed.

Uploading a local source build to the PPA Launchpad builder farm is still a simple invocation of 3 commands: uupload, dpkg-buildpackage, and dput. It's probably better that we maintain control of this step for now.

Once we're comfortable with the Bamboo script, we can expand it to sync to PPA and Pantry...

**Comment by benjaoming** [comment]
Btw. you can still sign the .deb's on Bamboo.

**Comment by cpauya** [comment]
Sorry @benjaoming, but I have no idea whether it's getting the assessment.zip or not and from where.

So far, these are the steps that the script does inside a docker container as per: https://github.com/mrpau/installers/blob/c36fb08abdd2b90447e6aff1f195f4c3d4b58f62/debian/docker/build_local/Dockerfile

```bash
...
# Steps
#   1. Check if kalite.zip is available or redownload and extraxt it to the working directory.
#   2. Run `python setup.py sdist --static` inside the `temp/ka-lite/` directory.
#   3. Run mk-build-deps -i -r -t 'apt-get -y' inside the `debian/control` directory
#   4. Run `debuild -b -us -uc` in the `ka-lite-source-0.16.6/kalite` directory for packaging.
#   5. Collect the *.deb in the `temp/installers` directory
...
```

Good to know that we can sign .debs on Bamboo too.  I have some questions though:

1. Do you agree that we only sign the .debs that are the official releases and we don't sign for every provisional/development buids on Bamboo - like what we do for the OS X / Windows installers?
2. If yes, then where do you think should we code-sign?  On Bamboo?  Then do the manual upload to Pantry?

**Comment by benjaoming** [comment]
1. Yes I do agree, what I meant was that in principle we could sign them, but there's not concern that anyone would verify their authenticity. It only makes a difference if we create a debian repo on the Bamboo server.

2. No I think the release process should be PPA upload => copy to Pantry.

The files on pantry reflect the actual build in the PPA repo:

screenshot from 2016-06-18 01 57 39

**Comment by benjaoming** [comment]
Side note:

I think that if we get things running smoothly on Bamboo we should consider automating the release process for Launchpad... but only once we're comfortable :) I dare not say that this is possible right now, if you look in the Debian source scripts, you'll find they're awfully complex, that's my main concern.

Also, all of these scripts need to be refactored to stop using khan_assessment.zip and use raw content packs. Haven't done that yet.. am not entirely sure of the consequences of this change.

**Comment by cpauya** [comment]
Noted @benjaoming - so our priority for now is to run this build script in Bamboo and publish the .debs as artifacts.  Thanks much for clarifying.

**Comment by benjaoming** [comment]
Thanks for inquiring @cpauya :)

**Comment by aronasorman** [comment]
Merging this for the 0.16.7 release!

**Comment by benjaoming** [comment]
This wasn't ready @aronasorman ?

I think it was still just a sketch, for instance the string "0.16.6" is hard-coded into 10 different places, that's hardly maintainable.

@arceduardvincent would you be able to finalize this work, at least so it grabs its version number from one location (either an environment or the built source).

For instance, the Windows version builds like this:

    KALITE_BUILD_VERSION=`python2 -c 'import version; print version.VERSION'` wine inno-compiler/ISCC.exe installer-source/KaliteSetupScript.iss

**Comment by benjaoming** [comment]
Btw should we base it on this docker image?

https://hub.docker.com/r/atlassian/bamboo-base-agent/

**Comment by arceduardvincent** [comment]
@benjaoming it is not finish yet. As of now I am doing something to be finish immediately.
I will work on it later.

**Comment by benjaoming** [comment]
#149

**Pull request merged**
