### PR TITLE
Add option `download_assessment_items_package`.

### LINKED ISSUE #22: Option to update the assessment items.
**Branch** Develop
**Target** 0.14.x
**Expected Behavior**
On the .app preferences dialog, put an option to update assessment items. 

And warn them that the `assessment.zip` is large at 400MB+, and show a download/update progress to be user-friendly.

**Update Steps**

1. Download the `assessment.zip` from https://learningequality.org/downloads/ka-lite/SHORT_VERSION/content/assessment.zip to `$KA_LITE_DIR/data/` folder or any arbitrary location as per user preference.
1. Run `bin/kalite manage unpack_assessment_zip` to unpack it.

**Notes**

1. The build server will generate a `ka-lite` folder which includes the assessment items already.  This folder will be used by the `setup.sh` script to include in the .dmg.
1. The `assessment.zip` is located at https://learningequality.org/downloads/ka-lite/SHORT_VERSION/content/assessment.zip -- example: https://learningequality.org/downloads/ka-lite/0.13/content/assessment.zip

### PR DESCRIPTION
**Pull request by cpauya**
Hi @aronasorman - this initially fixes #22 - "Option to dowload the assessment items package.".

We can now pass `download_assessment_items_package` on the setup script so that the assessment items package will be included in the to-be-built installer.

To use, just run `./setup.sh download_assessment_items_package`, the script will detect if the `$KA_LITE_DIR/data/assessment.zip` does not exist and downloads it from https://learningequality.org/downloads/ka-lite/SHORT_VERSION/content/assessment.zip then adds it to the above directory.  For verbosity, a valid assessment pack archive for version 0.13 is at https://learningequality.org/downloads/ka-lite/0.13/content/assessment.zip

With the `assessment.zip` included, the installer .dmg is now 370MB+ and the .app is 560MB+ in size.  For comparison, the previous .dmg size was 51MB+ and the .app was 130MB+.

ToDos:
- [ ] Modify the .app to check if `$KA_LITE_DIR/data/assessment.zip` exists and run `bin/kalite manage unpack_assessment_zip`.
- [ ] Add option to allow user to re/download the package from https://learningequality.org/downloads/ka-lite/SHORT_VERSION/content/assessment.zip to "force update" whatever is already installed.

### CODE REVIEW

**Comment by aronasorman** [comment]
Hehey! We just changed the URL of the assessment items from eslgenie to the pantry: https://github.com/aronasorman/ka-lite/blob/2e5bfdeee78f4527bd668e2c2e0a6ae4e525690d/kalite/settings.py#L223

We also make the default name of the assessment item zip to `assessment.zip`.

**Comment by cpauya** [comment]
Thanks for the tip @aronasorman - will use those then.

**Comment by aronasorman** [comment]
Is this good to go for review @cpauya?

**Comment by cpauya** [comment]
Hi @aronasorman - I will work on the first task above today: "Modify the .app to check if `$KA_LITE_DIR/data/assessment.zip` exists and run `bin/kalite manage unpack_assessment_zip`", then this should be good for review.

For now, you can run `./setup.sh download_assessment_items_package` to check if the `assessment.zip` is included in the built installer / .dmg.

**Comment by cpauya** [comment]
As per discussion with @aronasorman - the build server will handle the extraction of the `assessment.zip` into a `ka-lite` folder which the installer will include on the `Resources` folder.

So we can remove this PR and work on providing the "update assessment items" feature of the .app.

**Pull request closed without merging**
