### PR TITLE
Hotfix/169 mac 0.15 dev assets are not compiled

### LINKED ISSUE #169: MAC 0.15 dev, assets are not compiled
Landing page after installation and subsequent reloading of application and server. Assets are not compiled. No way to login?

### PR DESCRIPTION
**Pull request by cpauya**
Hi @aronasorman - this fixes #169 "mac 0.15 dev assets are not compiled".

We moved the step to run `pyrun setup.py install` after running the `node build.js` so that the `bundle*.js` files are included when copied inside the `pyrun-2.7` directory.

`bundle*.js` files are now bundled in the KA-Lite-Monitor.app:

```bash
cyril-lappy6:~ cyril$ cd /Applications/KA-Lite-Monitor.app/
cyril-lappy6:KA-Lite-Monitor.app cyril$ find ./ -name "bundle*.js"
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/coachreports/static/js/coachreports/bundles/bundle_coach_report.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/coachreports/static/js/coachreports/bundles/bundle_student_progress.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/control_panel/static/js/control_panel/bundles/bundle_clock_set.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/control_panel/static/js/control_panel/bundles/bundle_data_export.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/control_panel/static/js/control_panel/bundles/bundle_facility_management.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/control_panel/static/js/control_panel/bundles/bundle_zone_management.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_audio.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_base.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_common.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_compatibility.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_document.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_exercise.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_homepage.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_learn.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_register_public_key_client.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/distributed/static/js/distributed/bundles/bundle_video.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/inline/static/js/inline/bundles/bundle_inline_help.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/updates/static/js/updates/bundles/bundle_update_languages.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/updates/static/js/updates/bundles/bundle_update_software.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/updates/static/js/updates/bundles/bundle_update_videos.js
cyril-lappy6:KA-Lite-Monitor.app cyril$
```

Running site on http://127.0.0.1:8008/
screenshot 2015-09-21 16 13 31

### CODE REVIEW

**Comment by cpauya** [comment]
Remaining tasks before this PR can be closed:

* [ ] The admin account set on the preferences window is not created.
* [ ] On the site, there's no Documentation link under the User menu.

**Comment by arceduardvincent** [comment]
Hi @cpauya I was able to fix the issue "Documentation link under the User menu". 
@djallado already test this fix and it work on his local machine.

**Comment by djallado** [comment]
Yes @arceduardvincent. The documentation link is now on admin menu. Here's my screenshot:
screen shot 2015-09-22 at 5 40 02 pm

**Comment by amodia** [comment]
@cpauya here's the updated checklist of the task you declared above.

Remaining tasks before this PR can be closed:

- [x] The admin account set on the preferences window is not created.
- [x]  On the site, there's no Documentation link under the User menu.

**Comment by djallado** [comment]
@amodia. I tested your fix and the admin account set on the preferences window is created.
Here's the screenshot when I click on `Open in Browser` menu. 
screen shot 2015-09-22 at 6 50 48 pm

**Comment by cpauya** [comment]
Great work guys!  Checking these out and will upload a built OSX installer on after.

**Comment by cpauya** [comment]
Hi @aronasorman - this is ready for your testing and merge.

**Comment by cpauya** [comment]
Merged this into `master` and later on `develop` so we can start using the `develop` branch for feature releases.

**Comment by aronasorman** [comment]
Looks good!

**Pull request merged**
