### PR TITLE
Hotfix/329 uninstall script does not delete the ka lite data folder

### LINKED ISSUE #329: Uninstall script does not delete the KA Lite data folder.
**Branch** develop

**Target** 0.16.0

**Expected Behaviour** The OS X uninstall script does not delete the KA Lite data folder even when user answers "yes" when asked.

**Current Behaviour** It doesn't delete the KA Lite data folder.

### PR DESCRIPTION
**Pull request by cpauya**
Hi @aronasorman - this fixes #329 "Uninstall script does not delete the KA Lite data folder".

It now deletes the KA Lite data folder, defaults to `~/.kalite/` folder or whichever was pointed to by the `KALITE_HOME` env var.

I've re-arranged the process to gather the files/folders to delete and it's confirmation, it will first confirm if user wants to delete the KA Lite data folder.  Then it will add that folder to the array of files/folders to delete.

The script now checks if the files/folders in the array exists and will not confirm or ask for admin password if they don't.

### CODE REVIEW

**Comment by cpauya** [comment]
FYI: @arceduardvincent :smile_cat:

**Comment by amodia** [comment]
@cpauya & @arceduardvincent I tested this PR on OS X YOSEMITE and it's working properly the uninstall script will now delete the .kalite directory.

**Comment by arceduardvincent** [comment]
Hi @cpauya .
I try to replicate the issue and this fix.
It works also on my machine it was able to delete the `~/.kalite/` data folder if you agree to remove the data path.

**Comment by cpauya** [comment]
Thanks guys, merging this now.

**Pull request merged**
