### PR TITLE
OSX Installer - use Packages

### LINKED ISSUE #144: Implement Mac Packages
**Branch**  `master`

**Target** `0.15.x`

**Proposal Description**
To use [Packages](http://s.sudre.free.fr/Software/Packages/about.html) project in our `KA-Lite Monitor` and able to create a configurable installer. As of now we are using the [create-dmg](https://github.com/mrpau/create-dmg) project which we can't configure. 

**Checklist**
- [x] Able to display the `README` and `License`
- [x] Able to create a configurable installer.
- [x] Modify `setup.sh`
- [x] Update `README`

The image below demonstrates the use of  [Packages](http://s.sudre.free.fr/Software/Packages/about.html).
screenshot 2015-08-26 13 01 47

### PR DESCRIPTION
**Pull request by arceduardvincent**
Hi @aronasorman and @cpauya.
This fixes #144.
Enhancement using [Packages](http://s.sudre.free.fr/Software/Packages/about.html) 

**Enhancement Checklist :**

- [x]  Show License
- [x] Show readme
- [x] Add pyrun
- [x] Add assessment.zip
- [x] Run setup.sh

**Steps to create the installer:**

 1. Open terminal
 2. Navigate to your `./installer/osx` folder.
 3. run `./setup.sh "https://github.com/learningequality/ka-lite/archive/0.15.x.zip" "https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip"`.
 4. open the build output `./installers/osx/temp/output/KA-Lite.mpkg`
 5. Install the newly built installer.
demo_installer

### CODE REVIEW

**Comment by cpauya** [comment]
@arceduardvincent Looking good as per yesterday's demo! 

Some notes:

1. Pls remove the use of `create-dmg` in the setup script and this should be good to go, we don't use it here anymore, right?
2. Let's not do the uninstall option here and do that as another issue.

**Comment by arceduardvincent** [comment]
@cpauya I update my recent changes according to your request above.

I think it is ready for merge  and I will create another `PR` for the uninstaller feature.

**Comment by aronasorman** [comment]
Does this use the sdist?

**Comment by cpauya** [comment]
Sorry not yet @aronasorman - it's still using the `pyrun setup.py install` approach.  

Should we be using `python setup.py sdist` already or perhaps we can create another issue for that so we can test it thoroughly?

**Comment by aronasorman** [comment]
The idea is for the installer to just accept an sdist in place of the full repo. From there I think you can just replace the `setup.py install` step to `pyrun -m pip install <sdist path>` to install it.

If this is working then we can merge it now, then work on the sdist after that as a separate issue.

**Comment by cpauya** [comment]
Cool, will review this one more time tomorrow.  Will create a new issue for using `sdist`.

@arceduardvincent was able to demo this as working but I'm wary about the so many commits going into `develop`.  If all is good, will merge it after.

**Comment by cpauya** [comment]
Closing, will work on #245 instead.

**Pull request closed without merging**
