### PR TITLE
OSX Installer - use Packages part 2

### LINKED ISSUE #144: Implement Mac Packages
**Branch**  `master`

**Target** `0.15.x`

**Proposal Description**
To use [Packages](http://s.sudre.free.fr/Software/Packages/about.html) project in our `KA-Lite Monitor` and able to create a configurable installer. As of now we are using the [create-dmg](https://github.com/mrpau/create-dmg) project which we can't configure. 

**Checklist**
- [x] Able to display the `README` and `License`
- [x] Able to create a configurable installer.
- [x] Modify `setup.sh`
- [x] Update `README`

The image below demonstrates the use of  [Packages](http://s.sudre.free.fr/Software/Packages/about.html).
screenshot 2015-08-26 13 01 47

### PR DESCRIPTION
**Pull request by arceduardvincent**
Hi @aronasorman and @cpauya.
This fixes #144.
Part 2 of #235
Enhancement using [Packages](http://s.sudre.free.fr/Software/Packages/about.html) 

**Enhancement Checklist :**

- [x]  Show License
- [x] Show readme
- [x] Add pyrun
- [x] Add assessment.zip
- [x] Run setup.sh

**Steps to create the installer:**

 1. Open terminal
 2. Navigate to your `./installer/osx` folder.
 3. run `./setup.sh "https://github.com/learningequality/ka-lite/archive/0.15.x.zip" "https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip"`.
 4. open the build output `./installers/osx/temp/output/KA-Lite.mpkg`
 5. Install the newly built installer.

### CODE REVIEW

**Comment by cpauya** [comment]
Looks good, let's schedule a demo @arceduardvincent.

**Comment by arceduardvincent** [comment]
Ok sir. I will demo today

**Comment by cpauya** [comment]
@arceduardvincent As per demo yesterday:

1. Fix the background logo, if hard, remove it for now.
2. Fix the payload to include the `ka-lite` app (.pkg is only 49kb?).

If done, let's demo again and this should be good to go. :smile_cat:

**Comment by cpauya** [comment]
@arceduardvincent Demo looks good, let's update the documentation then this should be good to go.

**Comment by cpauya** [comment]
Looks good, merging.

**Pull request merged**
