### PR TITLE
Merged master into develop

### PR DESCRIPTION
**Pull request by amodia**
@cpauya & @MCGallaspy I resolved the conflicts on this PR #254

### CODE REVIEW

**Comment by cpauya** [comment]
@amodia You are missing some diff from @MCGallaspy's PR: https://github.com/learningequality/installers/pull/254/files#diff-d562dae67b82d38f2c9b698b83f5c84cR374

**Comment by cpauya** [comment]
Sorry, leave that.  @MCGallaspy please verify if your changes are here.

**Comment by djallado** [comment]
@amodia I tested your PR in my local, it builds the KA-Lite.pkg in output directory.
I also installed the KA-Lite.pkg and its working.

**Comment by cpauya** [comment]
Looks good, merging this then we must work to resolve the conflicts on `master` branch for #254.

**Pull request merged**
