### PR TITLE
Win installer use content pack

### PR DESCRIPTION
**Pull request by MCGallaspy**
## Summary

Updates the windows installer to both use content packs, and to use an sdist that has been downloaded from e.g. PyPI (or built locally and made accessible to the installer by copying it to the installers/windows directory).

@radinamatic let me re-configure the build server and then we'll be ready to test this out.

## TODO

- [X] Added/updated the documentation. (Updated the readme!)

P.S. I feel like this PR template is maybe not so relevant to this repo?

### CODE REVIEW

**Comment by radinamatic** [comment]
@MCGallaspy Ping me with the build number that I should download!

PS: You are right, I may have gone overboard with PR template "verbosity"... But the docs and readme items on the TODO are relevant, no?

**Comment by MCGallaspy** [comment]
It seems there's a problem because the English language content pack is not available on the build server -- @aronasorman is the plan to build it on the build server? Or should I re-configure the windows installer build to instead get it from pantry?

**Comment by aronasorman** [comment]
It's failing on the build server right now. I'll get it working again hopefully by today, but if you need it building very soon I recommend shifting to pantry for now.

**Comment by MCGallaspy** [comment]
@radinamatic build 150 is ready: http://dungeon.learningequality.org:8085/browse/KL-KALITE016-150/artifact

For now, we just want to test out that installation succeeds and content (assessment items, etc) are visible. This and later builds can then be used for more comprehensive testing of the application.

**Pull request merged**
