### PR TITLE
Put version in KA-Lite Preferences dialog.

### LINKED ISSUE #255: Put KA-Lite version at the right side of KA-Lite logo.
**Branch:** `Develop`

**Expected Behavior:** Must have a version in `KA-Lite Preferences` dialog.

**Current Behavior:** No `KA-Lite` version in `KA-Lite Preferences` dialog.

**Steps to reproduce:**

1. Launch `KA-Lite` app from the `Applications` folder.
2. Click `Preferences...` in menu bar.
3. A `KA-Lite Preferences` dialog will appear. 
screen shot 2015-11-05 at 1 53 21 pm

Notice that the `KA-Lite Preferences` dialog don't have a version.

### PR DESCRIPTION
**Pull request by djallado**
@cpauya, This fixes #255.

### CODE REVIEW

**Comment by cpauya** [comment]
Some questions:

1. This is still hard-coded version right @djallado?
2. Can you attach a screenshot?

**Comment by djallado** [comment]
Yes, the version is hardcoded. 

**Screenshots:**
Before:
scrnb4

After:
scrnafter

**Comment by cpauya** [comment]
@djallado Can you remove the underline and the colon for the texts?

**Comment by djallado** [comment]
I remove the underline and colon in version label. I also resize the version label.
Here's the screenshot:
screen shot 2015-11-09 at 1 54 46 pm

**Comment by cpauya** [comment]
Looks better @djallado, merging. :+1:

**Pull request merged**
