### PR TITLE
[Windows] Change CONFIG.dat file location, behavior

### LINKED ISSUE #321: Failed to create config file/option alerts on Windows installer
"Failed to create config file/option" alerts

**Branch**: 0.16 installer (build # 81) on Windows 7 & 8 

**Current Behavior**:  

Two error alerts appear when KA Lite is started from the desktop shortcut:
config
option

Both errors alerts appear twice (1st, 2nd, 1st, 2nd), but after that KA Lite appears in the Taskbar notification area, and can start the server correctly.

### PR DESCRIPTION
**Pull request by MCGallaspy**
Still a WIP. Will fix #321.

Todo:
- [x] Remove the ability to create CONFIG.dat at install time
- [x] Write CONFIG.dat to a location determined by the user running KA Lite.exe
- [x] Do some clean-up refactoring on `config.h`.
- [x] Migrate data from location dependent on Windows version to installing user's ~/.kalite dir.
- [x] Change the start at boot option so that it run's as the current user instead of SYSTEM

Will appreciate a code review. I am but an egg with C++\Windows dev. Willing to discuss in great detail.

### CODE REVIEW

**Comment by radinamatic** [comment]
> I am but an egg with C++\Windows dev

Then I must be a proto-idea of an egg... :stuck_out_tongue: 
Ping me as I want to sit in on that code review!

**Comment by MCGallaspy** [comment]
@radinamatic this should almost be ready for testing. I just want to give it a sanity check before unleashing you on it in full force.

**Comment by radinamatic** [comment]
> before unleashing you on it in full force.

This makes me sound like a bloodhound. You guys must still see me as an enforcer of sorts  :stuck_out_tongue_winking_eye:

**Comment by MCGallaspy** [comment]
> We still have pending the issue of how is KA Lite going to be started, right?

Yes. Let me add an item for that. That said, it shouldn't affect this too much. Can you download the installer, and ensure that it just *installs* okay, then I'll push that change and we can start testing upgrading/start at boot behavior?

**Comment by MCGallaspy** [comment]
Once I push the change, I'd like to test it out like the following scenarios:

- [ ] Test "fresh" installs on each version of Windows*.
- [ ] Test upgrading on at least one version of windows for 0.12.
- [ ] Test upgrading on at least one version of windows for 0.13.
- [ ] Test upgrading on at least one version of windows for 0.14 *when the user has already used the start at boot option* (and thus has data in the SYSTEM's profile which must be migrated).
- [ ] Test upgrading on at least one version of windows for 0.15 *when the user has already used the start at boot option*.

Maybe others?

**Comment by radinamatic** [comment]
Sounds fine by me, to begin with.. If something pops up that needs a more specific scenario, we'll get to it after this...  

If you didn't push this, should I still test the # 101 build?

**Comment by MCGallaspy** [comment]
@radinamatic should be good to go with build 102.

**Comment by radinamatic** [comment]
Ok, will download now and start testing tomorrow! :+1:

**Comment by radinamatic** [comment]
Hm, the version check might not be working correctly: it seems to [detect](https://github.com/MCGallaspy/installers/blob/56fb381c9f08b8d9cbeb875c9a9a9e73610a4359/windows/installer-source/KaliteSetupScript.iss#L174) the previous installation on VM screenshots (of 2 different Windows 7 machines) that do not have any.

I've searched the registry for any `KA Lite` keys/values, and found only a couple which I suppose are some kind of cache for the current build instal. (screenshot coming). @MCGallaspy

**Comment by radinamatic** [comment]
And no wonder it reports an error afterwards:

ie9 - win7 ready for ka lite running - oracle vm virtualbox_144

**Comment by radinamatic** [comment]
Regarding the `Something went wrong...` in the previous screenshot: this is one of my personal pet peeves, because of its total uselessness for the user. 

In case of legit upgrade scenario (and not with detection of non-existing previous installation), at this point the installer should include the option for the users to choose the content folder themselves. Could we try to implement that?

**Comment by radinamatic** [comment]
On another hand, # 102 installer behaves the same on Windows XP. This time though, I choose not to "upgrade", and the installer could not proceed (screenshot coming).

**Comment by MCGallaspy** [comment]
> In case of legit upgrade scenario (and not with detection of non-existing previous installation), at this point the installer should include the option for the users to choose the content folder themselves. Could we try to implement that?

Yeah, this is a legitimate point. Please open an issue for it, I'd like to address it separately.

**Comment by MCGallaspy** [comment]
I think both the issues you reported stem from the fact that an "upgrade" was attempted on a fresh install. Submitting a patch shortly.

**Comment by radinamatic** [comment]
#341 issue opened.

**Comment by MCGallaspy** [comment]
The above issues should be fixed, let's try again.

**Comment by radinamatic** [comment]
Ok, waiting for the new build to finish, since I did not have any luck with upgrade scenario from 0.14.2 to 0.16 (build # 102)... Installation finishes with no errors (there is room for improvement for the info offered to the user during the upgrade, but it seemingly ends without reporting any errors), but the server is not starting. It ends up eating progressively more resources, but no python process is raised after 15 minutes...

**Comment by MCGallaspy** [comment]
>  the server is not starting. It ends up eating progressively more resources, but no python process is raised after 15 minutes...

Can you elaborate? KA Lite ends up using more and more memory? How did you achieve that state?

**Comment by radinamatic** [comment]
Not KA Lite.exe, but one `svchost` process after I try to start the server from the task tray. Since there nothing else installed or going on this machine, I hazarded a guess it has something to do with it.  

ie9 - win7 some content running - oracle vm virtualbox_153

**Comment by radinamatic** [comment]
@MCGallaspy I can confirm that build # 104 is not starting the upgrade on "fresh" snapshot when there is, in fact, nothing to upgrade. Tested on W7, will confirm on XP and try the "real" upgrade scenarios tomorrow.

**Comment by MCGallaspy** [comment]
Groovy, please let me know if that server fails to start with this latest patch too :)

**Comment by radinamatic** [comment]
# 104 works well on "fresh" WXP and W8 snapshots, but the upgrade from 0.14.2 gave me a weird VM loggoff... :stuck_out_tongue_closed_eyes: 

Going to restart and try again, maybe VM's cables got crossed.

**Comment by radinamatic** [comment]
Ok @MCGallaspy, I might have figured out why I was getting the VM logoff while testing the upgrade scenarios. It took a couple of trys & fails, as it was showing that typical popup Windows application error with some code, but just for a second before logging off and shutting down. At one point I finally decided to disable the start on boot (because it was taking too long to start after system restart), and voilà, the upgrade finished OK. So the upgrade process must be creating some conflict **IF** the kalite server is running in the background. Could you set the installer to check if the server is running and stop it prior to upgrading? 

Then I remembered that Windows has the "restart after error" activated by default (it's been a while that I installed win machines for real use :stuck_out_tongue_winking_eye: ), so trying to figure out what exactly was the error, I reverted the snapshot and deactivated that option. I managed to get through the upgrade OK, but there was no popup Windows application error this time, just at some point of the `Running setup.py install for ka-lite-static` step there was a flash of command line output in red too brief to see the details, and the next step (`Unpacking...`) appeared. So if we want to find out what exactly is going on here, you'll have to leave some debugging space. 

Other than that, upgrade from 0.14.2 on Windows 7, from both admin system user and my "coach" system user did not give other errors. However, even though previous language packs are present and working, I can't seem to be able to see videos that I had under 0.14.2. `Scan content folder for videos` does not seem to be doing anything, but I am unsure that feature was implemented in the first place...

**Comment by MCGallaspy** [comment]
Thanks for the info, will continue debugging.

**Comment by radinamatic** [comment]
Ok, I'll try this build for upgrades from 0.15/0.13 to see if something else can help.

**Comment by radinamatic** [comment]
`Scan content folder for videos` error:

ie9 - win7 coach upgraded to 0 16 running - oracle vm virtualbox_175

Error after logging in as Learner:

ie9 - win7 coach upgraded to 0 16 running - oracle vm virtualbox_176

**Comment by radinamatic** [comment]
Upgrade from 0.15 to 0.16 (build #104) shows exactly the same behavior as from 0.14.2, from the installation error right to the errors in the screenshots above. I'm going to try and stop/disable the server prior to install to see if that changes anything.

**Comment by radinamatic** [comment]
###### Upgrade from 0.15 to 0.16 (build # 104) on W7 

Test case with KA LIte task disabled and installation performed after restart, meaning the **server was not running** during install as in previous cases.

Result:
No command prompt errors during the installation which seems to confirm the hypothesis that server should be stopped. 

However, after the installation and restart, KA Lite is unable to start the server from task-tray. When I observe processes in Task Manager window, I see 2 python processes appearing briefly and then disappearing.

**Comment by radinamatic** [comment]
###### Upgrade from 0.13 to 0.16 (build # 104) on W7 

Contrary to what I expected, this upgrade installation went without any errors, even though the server was active in the background during the installation, and after the restart the server is starting A-OK...! :)

However, the langpack content that was available in 0.13 is not recognized, I see that the videos got transferred correctly, but cannot be seen in the sidebar (it results empty as in all the upgrade test cases).

**Comment by MCGallaspy** [comment]
@radinamatic I started trying to replicate your issue with upgrading from 0.14.2 to 0.16.0 -- I can't seem to get the start at boot option to work *at all* on Windows 7 using 0.14.2. Did you have the same experience?

**Comment by MCGallaspy** [comment]
> I can't seem to be able to see videos that I had under 0.14.2

It may be that the videos were erroneously copied from the SYSTEM's `.kalite` dir rather than the your regular user's `.kalite` dir, if you had been both starting KA Lite through the scheduled task as the SYSTEM user and manually starting KA Lite as the regular user. Can you elaborate on how you "prepared" the 0.14.2 installation before upgrading, particularly if you had been using the start-at-boot feature vs. starting the server manually?

**Comment by MCGallaspy** [comment]
I should rather say that starting KA Lite using the scheduled task doesn't fail using 0.14.2 on W7 doesn't outright fail, but it appears to be either hung or incredibly slow.

**Comment by radinamatic** [comment]
###### Upgrade from 0.12 to 0.16 (build # 104) on W7 

This upgrade installation too seems smooth and goes on without errors, but as far as I understand version 0.12 did not have the option to start on booth, so there wasn't a running server in the background to interfere with.

The same as for 0.13, previously available langpack does not appear under `Manage > Languages`, and topic tree for videos is unavailable despite them being migrated correctly to the new `.kalite/content ` folder. Sidebar is empty as in all the previous upgrade test cases.

**Comment by radinamatic** [comment]
> scheduled task doesn't fail using 0.14.2 on W7, but it appears to be either hung or incredibly slow.

And I thought that was just me... :stuck_out_tongue: 
Yes, on my VM it can take up to 10 minutes to actually start.

**Comment by MCGallaspy** [comment]
The mystery deepens -- you had earlier indicated a bloated svchost.exe task, which I also saw. I killed it and KA Lite's python process went from unresponsive to quite happy, but then it sprang up again. It might be unrelated -- it's the host process in charge of Scheduled Tasks, but it seems unlikely that KA Lite is the cause because the KA Lite scheduled tasks finishes quite quickly after spawning the python process.

**Comment by radinamatic** [comment]
I think that the bloated `svchost.exe` task was Windows Update on my VM, and after I kill the service itself (together with `Windows Module Installer` one), the whole system works much better. I'm adding that to my tutorial... :wink:

**Comment by MCGallaspy** [comment]
I still can't seem to make any headway successfully running KA Lite 0.14.2 as the SYSTEM user on Windows 7. I've resorted to downloading a different Windows image to test it out, will report results here.

**Comment by radinamatic** [comment]
Retested the 0.14.2 on completely new Windows 7 VM. Start on boot option works when I install, restart and login as the default admin user on modern.ie images (IEUser). Scheduled task itself is run by the SYSTEM user:

system

**Comment by radinamatic** [comment]
Testing start on boot for 0.14.2 on XP, and failing, independent of logged in user. 

@EdDixon do you recall if that used to work?

**Comment by EdDixon** [comment]
I can not remember. I was thinking that there was a fix at some point during 0.14 development but it may not have worked out for a release. I wish I could provide more information about this. As I recall Rui had made some changes to the binary and its affect on the windows registry that made that possible. 


Sent from Outlook Mobile






On Fri, Jan 15, 2016 at 10:49 AM -0800, "Radina Matic" <notifications@github.com> wrote:












Testing start on boot for 0.14.2 on XP, and failing, independent of logged in user. 



@EdDixon do you recall if that used to work?

**Comment by radinamatic** [comment]
Retested the 0.14.2 on completely new Windows XP VM. Start on boot option selected in the installer does not work with scheduled task run by the `NT AUTHORITY\SYSTEM` user:

**Comment by MCGallaspy** [comment]
@radinamatic okay, don't spend too much time on 0.14.2 on XP, I'll see if I can replicate the failure myself. I was able to get 0.14.2 working fine re: start at boot on W7 using a different image. Not sure what my original issue was, but I'll move on for now.

**Comment by MCGallaspy** [comment]
Some updates:

I tried 0.14.2 -> 0.16.0 on W7. I didn't get any errors during installation as you reported, but that still concerns me! Can you try to identify how to replicate that behavior?

That said, I did notice two things:

1. I enabled the start at boot option, but it didn't work! It seems that (for me) the "Run only when user is logged on" option is enabled by default, which of course fails at system start.
2. I was *also* missing video content from the "Learn" page -- the sidebar was blank -- but that's because dev for 0.16.0 isn't yet done! Sorry, I should have warned you, @radinamatic. Unless you experienced a different error? You can at least check the `~/.kalite/content` dir to see if the videos are there. I verified on my own test run that they were, so I'm reasonably confident that copying SYSTEM data to user's .kalite dir works reasonably well. :)


Let me try out upgrading from other version -> 0.16.0, then we'll take stock again.

**Comment by radinamatic** [comment]
> I tried 0.14.2 -> 0.16.0 on W7. I didn't get any errors during installation as you reported, but that still concerns me! Can you try to identify how to replicate that behavior?

After several tryouts the only thing that I can conclude is that it happens only if the server is already running in the background, which is to be expected if the previous 0.14.2 installation is set to start on boot, and user did not expressly stop the server and python processes prior to upgrading to 0.16. When I did that test case (manually stopping the 0.14 server), or when I had 0.14 version which was not set to start on boot, no errors appeared during the upgrade.

**Comment by radinamatic** [comment]
And if you have the "Automatically restart the system after errors" checkbox (in Advanced system recovery options) deactivated, you will not even see the error unless you watch carefully the cmd window while it executes the `Running setup.py install for ka-lite-static` step, as it is really one super-fast flash of command output in red and then the next terminal window appears. Trust me, I tried several times to figure it out, take a screenshot or even snap a photo of it with my camera, but it was always too damn fast... :angry:

**Comment by radinamatic** [comment]
> that's because dev for 0.16.0 isn't yet done! Sorry, I should have warned you, @radinamatic. Unless you experienced a different error? 

No worries, I figured a lot of 0.16 core features are still in the making. Videos are safely in the `~/.kalite/content` folder so I guess we wait for the new 0.16 to finally confirm that it's working.

**Comment by MCGallaspy** [comment]
I did indeed try upgrading while 0.14.2 KA Lite was still running, but my system didn't crash. Also the red text that appears in the cmd prompt during the `Running setup.py install for ka-lite-static` step is *also* not an error, just an unfortunately worded message.

Sorry, but I'm not able to replicate the crash -- can you perhaps try to get a VM in a state just prior to the crash, ensure that it happens consistently, and then we'll see about uploading the image somewhere so I can further debug it?

>And if you have the "Automatically restart the system after errors" checkbox (in Advanced system recovery options) deactivated

I'm not familiar with this option and I couldn't seem to find docs for it (for W7). Can you describe how to enable/disable it?

**Comment by radinamatic** [comment]
Did you also try the upgrade from 0.15 to 0.16? I had the same "logoff" error there too? 

Let me fetch a screenshot of that "Automatically restart the system after errors" option.

**Comment by radinamatic** [comment]
@MCGallaspy 

auto-restart

XP, but it's in the same place on 7 & 8.
It's activated by default when you install Windows - I guess they are too lazy to give a meaningful feedback to the user about what went wrong... :unamused:

**Comment by radinamatic** [comment]
Ok, after several more tryouts, I wasn't able to reproduce it consistently... :unamused: 
The only thing I can say is that it appears when I try to install the upgrade while logged in as a "standard" Windows user, not one with admin rights, and even then maybe only 50% of the times. Maybe it has something to do with my testing machine and not with the installation itself. 

The only thing that I can see remaining to try is to download a completely new VM image and make one last upgrade test from 0.14 to 0.16. Will report back after.

**Comment by radinamatic** [comment]
@MCGallaspy I'd forget about that error while upgrading on W7 for now, as I couldn't replicate it on a completely new W7 image, a new 0.14.2 install and upgrade to 0.16. Error is there, and even though it doesn't force logoff/restart of the VM, this time I managed to see a bit more of that error terminal output in red and even catch a glimpse of a phrase, something like "folder not available" or "folder not present" at the end... You said that it was an "unfortunately worded message", do you have the exact wording of that message?

**Comment by MCGallaspy** [comment]
> You said that it was an "unfortunately worded message", do you have the exact wording of that message?

Yeah, if you check in the Program Files directory where KA Lite is installed, you should find a zipfile called something like `ka-lite-static-0.16.0.zip`. If you open a command prompt and type the command `pip install <filename>` with that file as the `<filename>` you should see the "unfortunately worded message". (You'll probably have to specify the full path to `pip`, on my system it's `C:\Python27\Scripts\pip.exe`.)

**Comment by radinamatic** [comment]
Ok, this is what I get with what you say above, and it looks pretty tame compared to what I see in that error during install:

```
C:\Program Files\KA Lite\ka-lite>C:\Python27\Scripts\pip.exe install ka-lite-sta
tic-0.16.0.zip
You are using pip version 7.0.1, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing c:\program files\ka lite\ka-lite\ka-lite-static-0.16.0.zip
  Requirement already satisfied (use --upgrade to upgrade): ka-lite-static==0.16
.0 from file:///C:/Program%20Files/KA%20Lite/ka-lite/ka-lite-static-0.16.0.zip i
n c:\python27\lib\site-packages

C:\Program Files\KA Lite\ka-lite>
```

The two lines `You are using pip version...` are yellowish, and all the rest is a normal white on black output. The flash of error output I saw during the installation after the `Running setup.py install for ka-lite-static` has about 10 lines and is all in bright red letters.

**Comment by MCGallaspy** [comment]
Try running `pip uninstall ka-lite-static` first, then installing it again -- I'll look closer into possible causes, perhaps I'm thinking of a different issue after all.

**Comment by radinamatic** [comment]
Nope, all seems fine here:
```
C:\Program Files\KA Lite\ka-lite>C:\Python27\Scripts\pip.exe uninstall ka-lite-static
You are using pip version 7.0.1, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Uninstalling ka-lite-static-0.16.0:
  c:\python27\lib\site-packages\ka_lite_static-0.16.0-py2.7.egg-info
  c:\python27\lib\site-packages\kalite
Proceed (y/n)? y
  Successfully uninstalled ka-lite-static-0.16.0

C:\Program Files\KA Lite\ka-lite>C:\Python27\Scripts\pip.exe install ka-lite-static-0.16.0.zip
You are using pip version 7.0.1, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing c:\program files\ka lite\ka-lite\ka-lite-static-0.16.0.zip
Installing collected packages: ka-lite-static
  Running setup.py install for ka-lite-static
Successfully installed ka-lite-static-0.16.0

C:\Program Files\KA Lite\ka-lite>
```

I tried the above with the server running in the background, and logged in as both admin Windows user and standard one with no admin rights, since it was there that the error occasionally appeared, but no dice... Maybe we should set this aside unless it starts raising its nasty head in a more consistent manner.

**Comment by MCGallaspy** [comment]
Okay, at this time I've managed to upgrade from 0.13 and 0.14 to 0.16 with apparent success inasmuch as this PR is concerned: meaning that:

* SYSTEM's profile is migrated to the installing user's profile if it exists (videos + user data)
* Xhanging options using the task-tray program no longer causes CONFIG.dat related errors. 

@radinamatic you still have quite a few unaddressed bugs, which I'll try to summarize shortly below. Additionally, I've also encountered at least one apparent *application* error from upgrading 0.13 -> 0.16, which I'll file elsewhere.

That said, I think if we set the bar for this PR to addressing the above points, then we can call it a success and consider the other bugs separately.

**Comment by MCGallaspy** [comment]
Additionally, it seems we must ensure the start-at-boot scheduled task is set to run whether the user is logged in or not (at least on Windows 7).

**Comment by radinamatic** [comment]
Ok, will re-testing if start-at-boot scheduled task executes correctly whether the user is logged in or not on Win 7/8. I think that so far it did work on 7, but I can't recall for Win 8.

**Comment by MCGallaspy** [comment]
We can tackle start at boot separately -- I just wanted to note it down. I would like specifically to test whether user data + content is migrated from the prior location to the user's .kalite dir, *and* that the task-tray config options work without error in 0.16. But looking more closely at the thread, it seems you already confirmed this for 0.12 and 0.15, yes? And I independently verified it for 0.13 and 0.14. If my understanding is correct, I think we should consider the other issues separately, as this thread is getting unwieldy.

**Comment by radinamatic** [comment]
Yes, user data + content is **seemingly** migrated from the prior location to the user's .kalite dir, and I haven't seen any task-tray config errors with installer # 104 in any upgrade scenarios. I say "seemingly" because videos and langpacks are there in the migrated .kalite dir, but are not functional with this installer. As soon this is solved we can definitely confirm that migration is, indeed, successful. 

And yes, we should start considering other issues separately, this discussion is getting too long to manage... :wink:

**Comment by MCGallaspy** [comment]
>  As soon this is solved we can definitely confirm that migration is, indeed, successful.

It won't be resolved in this PR, it's an application issue.

> And yes, we should start considering other issues separately, this discussion is getting too long to manage... 

Agreed, I'll open separate issues and close this one once I get someone to review it.

**Comment by MCGallaspy** [comment]
@rtibbles consider this a last effort to get a reviewer -- if you're not able or willing in the next few days, could you kindly just press the "merge" button for me?

**Comment by MCGallaspy** [comment]
These should cover known errors @radinamatic, any that I missed here?

* https://github.com/learningequality/installers/issues/346
* https://github.com/learningequality/installers/issues/347

**Comment by radinamatic** [comment]
Yes, that about covers it, #346 is about same as my #345...?

**Comment by MCGallaspy** [comment]
Note to self: update build server installers branch to build from.

**Pull request merged**
