### PR TITLE
Hotfix/373 higher priority osx installer tweaks

### LINKED ISSUE #369: KA Lite Monitor app after upgrade
## Summary

If KA Lite Monitor app is active/open during the upgrade to 0.16, it does not get updated. Once installation finishes and user opens it from the icon in the status bar it will display the older version. When user tries to start the server the app replies with "Starting the server" but then it closes and disappears.
@cpauya 

I would recommend adding the step to installer to close the Monitor if it is opened prior to starting the actual upgrade process.

## Branch or installer

Upgrade scenario form 0.14.2 to 0.16 on OSX Yosemite.

## Screenshots

after_upgrade_yosemite_10_10_5

### LINKED ISSUE #370: KA Lite Monitor notifications
## Summary

Since VMs can be slow I don't always follow all the notifications with expectations, but go and multitask while they are working... :wink: 

Anyhow, I did notice that the messages `KA Lite stopped` and `You can now open the browser...` sometimes appear when the user is not expecting them. For example:

1. Server is stopped - user opens the menu and chooses `Start KA Lite`
   - first message appears: `Starting...`
   - then `Stopped` appears, but the icon is representing the running state and
   - no `You can now open the browser...` message 

2. Server is running  - user opens the menu and chooses `Stop KA Lite`
   - first message appears: `Stopping...`
   - then `You can now open the browser...`
   - finally the `Stopped` appears

## Branch or installer

0.16 (build 66) on (I think) all versions of OSX. 

## Screenshots

This would require captured video, do you have any Mac app suggestion for that  @cpauya?

### LINKED ISSUE #373: Higher-priority OSX installer tweaks
## Summary

- [x] At the end of the beautiful installer GUI wizard, tell the user what to do next. E.g. "Now that KA Lite is installed, you can start/stop the server, and launch the browser, from the leaf icon in your task tray" (or whatever that row of little icons is called on a Mac)
- [x] Launch the KA Lite app as soon as the installer finishes.
- [x] Auto-start the server whenever the KA Lite app is loaded.
- [x] Have the default behavior be to auto-launch the KA Lite app at boot (but still allow them to disable it, by unchecking that box under preferences)

## Branch or installer

@aronasorman demoed the latest 0.16.x candidate OSX installer to me (yesterday).

### PR DESCRIPTION
**Pull request by cpauya**
## Summary

- still a WIP
- fixes #373 
- fixes #370 - the "Stopped" notification during initial application load - specifically, https://github.com/learningequality/installers/issues/370#issuecomment-193492995
- fixes #369 

## TODO

> PR is considered WIP (work in progress), until all TODOs are marked.
- [x] Launch the KA Lite app as soon as the installer finishes.
- [x] Auto-start the server whenever the KA Lite app is loaded.
- [x] Have the default behavior be to auto-launch the KA Lite app at boot
- [x] At the end of the beautiful installer GUI wizard, tell the user what to do next.  This could be moot if we show the proper notifications to the user since we already auto-load and auto-start the app after installation.
- [x] Added/updated the documentation.

## Reviewer guidance

- Use the latest build of the OS X Installer (.pkg) at Bamboo to test this PR at http://dungeon.learningequality.org/browse/KL-MT16 -- build must be > 77.

### CODE REVIEW

**Comment by cpauya** [comment]
Hi @radina - I'm done with functionalities on this PR and it can now be tested.  Sadly the dungeon server is still down and hopefully @aronasorman can help fix it so you can download a .pkg to test.

I will follow working on the documentation after our team Alpha tests here in the office. :smile_cat:

**Comment by cpauya** [comment]
I've finally managed to customize the Summary step of the OS X GUI installer.  Here's a screenshot:

screenshot 2016-03-18 19 15 47

Please test the build 85 at http://dungeon.learningequality.org/browse/KL-MT16-85 for the latest updates.

**Comment by cpauya** [comment]
This PR now also fixes #369 by:

1. showing a "NOTE: Make sure that the KA Lite application is not loaded before continuing." at the Introduction section;
2. failing the install process if we find a loaded "KA Lite" application.

/cc: @radinamatic

**Comment by radinamatic** [comment]
Thanks @cpauya, I'll download the latest build as soon this is merged to try it out! :+1:

**Comment by cpauya** [comment]
Hi @radinamatic - [build 87 on Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-87) should include the fix for #369.  

Although the .pkg is still pointed to our repo's hotfix branch, once this is merged, I'll point it back to this repo's `develop` branch before building a .pkg that you can test.

Can I ask who should check and merge this?  Or should I still be the one to do it? :smile_cat: 

/cc: @aronasorman

**Pull request merged**
