### PR TITLE
Unknown command "migrate"

### LINKED ISSUE #61: Unknown command "migrate"
**Branch:** Master
**Expected behavior:** It must have a migrate command to run the `ka-lite` migration. 
**Steps to reproduce:**
 1. Required `windows xp sp3` Operating systems.
 2. Build `kalitesetup.exe` using `make.vbs`.
 3. Install the `kalitesetup.exe`.
 4. Open Command line and manually run `kalite start` at `program files\ka-lite\bin` directory.

screen shot 2015-06-15 at 3 48 49 pm

### PR DESCRIPTION
**Pull request by amodia**
Hi @aronasorman & @MCGallaspy this fixes #61 

I add the `KALITE_DIR` to windows environment variables and update the name of pip dependency zip file.

### CODE REVIEW

**Comment by amodia** [comment]
@aronasorman I have difficulty to use `glob` in pip dependency zip file name during the installation, Any other idea on this?

**Comment by aronasorman** [comment]
I believe `glob` should be included by default in python. If `glob` doesn't work, try using `fnmatch` instead.

**Comment by MCGallaspy** [comment]
I'm not convinced this is necessary. I have not had this issue, albeit I have only built and tested the installers on Windows 8. I would like someone to reproduce this issue on XP (assuming that is the problem) using a known good installer.

**Comment by amodia** [comment]
@aronasorman You commented on my old [PR](https://github.com/learningequality/installers/pull/54#discussion-diff-31943080) that the zip file name is hardcoded. So I find a way to use `glob` as your suggestion but its hard for me to implement that on `pascal`. But I observe that there's `MyVersion` variable so I used it on the zip file so  is not hardcoded.

screen shot 2015-06-25 at 6 25 39 pm

@MCGallaspy I asked @djallado to reproduce this issue on `Windows XP` tomorrow. Hope he might give us feedback.

**Comment by cpauya** [comment]
@amodia Good find! :+1: 

Minor request: Can you please change `getKALiteVerion()` to `getKALiteVersion()` and push your commit on this same PR?  It's wrong and confusing.  [Here's the source.](https://github.com/mrpau/installers/blob/hotfix/61-unknown-command-migrate/windows/installer-source/KaliteSetupScript.iss#L9)

screenshot 2015-06-26 09 11 59

**Comment by MCGallaspy** [comment]
@amodia the hardcoded version number is a separate issue. Can you open a PR with that fix?

**Comment by MCGallaspy** [comment]
Oops, sorry, silly me! Disregard the previous comment!

**Comment by cpauya** [comment]
Stale PR, let's re-create if issue persists.

**Pull request closed without merging**
