### PR TITLE
Upgrade process for OS X installer 0.16.0

### LINKED ISSUE #282: plist files are not deleted during the upgrade to 0.16.x.
**Branch:**  `develop`

**Expected Behavior:** During upgrade, the installer will remove the `org.learningequality.kalite.plist` in root `/Library/Launchagents/`.

**Current Behavior:**  Root `/Library/LaunchAgents/` still contains `org.learningequality.kalite.plist` during the upgrade.

**Steps to reproduce:** 
1. Use fresh install `Yosemite` in virtual machine.
2. Install `0.15.0.dmg`.
3. Launch `KA-Lite-Monitor` from `Applications` folder. 
4. Click `Start KA Lite` from the menu item.
5. Click `Open in Browser` menu item when ready, and Navigate in the browser to check if it is working. 
6. Click `Quit` from the menu item.
7. Install `0.16.0.pkg`.
8. After a successful installation, Launch `KA-Lite` from `Applications` folder. 
9. Click `Start KA Lite` from the menu item.
10. Observed that there's an error in the app.
11. Find `org.learningequality.kalite.plist` from root `/Library/LaunchAgents/`.
screen shot 2015-11-25 at 10 19 07 am

`org.learningequality.kalite.plist` is not deleted in root `/Library/LaunchAgents/`.

### PR DESCRIPTION
**Pull request by arceduardvincent**
Hi @aronasorman, @cpauya and @djallado .
This fixes #282 

**Upgrade Checklist :**
- [x] Remove /Library/LaunchAgents/org.learningequality.kalite.plist.
- [x] Remove existing KA-Lite-Monitor.app in /Applications folder
- [x] Retain .kalite

### CODE REVIEW

**Comment by djallado** [comment]
@arceduardvincent I tested your branch in my virtual machine. I installed `0.15.0` and download some videos, then logout and quit from the app. When I upgrade to `0.16.0`, I observed that:
1. The `/Library/LaunchAgents/org.learningequality.kalite.plist` from root was deleted.
2. The `KA-Lite-Monitor.app` in `/Applications` folder was removed.
3. The `.kalite` is still in the home directory, and my downloaded videos is still in the `content` folder of `.kalite`.

**Comment by cpauya** [comment]
So this is good to go then @djallado?  Coz we intend to use this during pre-installation for the 0.16.x installer.

**Comment by djallado** [comment]
@cpauya That's good to go. Here's the screenshot of my updated app. 
screen shot 2015-11-26 at 10 45 05 pm
The video I downloaded in 0.15.0 is still in the `content` folder of `.kalite` when I upgrade to `0.16.0`.

**Comment by cpauya** [comment]
Looks good, merging.

**Pull request merged**
