### PR TITLE
Use of retrievecontentpack on post install script of OS X installer

### LINKED ISSUE #358: Use of retrievecontentpack on post install script of OS X installer.
**Branch** develop

**Target** 0.16

**Operating System** Mac OS X

**Expected Behaviour**  Use `kalite retrievecontentpack local en path-to-en.zip` for content items.

**Current Behaviour**  We used `kalite manage init_content_items --overwrite` to populate content items.

I modified the OS X installer's post install script to replace the `kalite manage init_content_items --overwrite` with `kalite retrievecontentpack local en path-to-en.zip` -- then built the .pkg, installed on a VM, and noticed that the `~/.kalite/content_databases/content_khan_en.sqlite` on a target VM still has zero bytes.  

I replaced it with the [content.db from Pantry](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/content.db), it's about 12MB+, restarted kalite, but the sidebar didn't display anything.

**What works**

When I ran `kalite manage retrievecontentpack local en path-to-en.zip` in the target VM - it works!  The `content_khan_en.sqlite` now has 81MB+ in size.

Running the same .pkg on the target VM twice works too and it also generates the same size.

**Questions**

1. Any idea why the diff in size between the local .sqlite generated with `retrievecontentpack` versus the one in Pantry's is so big?
2. There is no tree of videos to download at Manage - Videos tab.

Setup of build (will make a PR for details of changes):

* used `ka-lite/0.16.x` branch
* used `installers/develop` branch
* build script now includes the [contentpacks/en.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip) along with the [assessment.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/khan_assessment.zip) when building the .pkg

On the side, the `KA-Lite.pkg` is now 691MB+ (with contentpacks/en.zip and assessment.zip) and will require at least 1.3GB+ when installed on a target Mac OS X machine.

/cc: @aronasorman

### LINKED ISSUE #370: KA Lite Monitor notifications
## Summary

Since VMs can be slow I don't always follow all the notifications with expectations, but go and multitask while they are working... :wink: 

Anyhow, I did notice that the messages `KA Lite stopped` and `You can now open the browser...` sometimes appear when the user is not expecting them. For example:

1. Server is stopped - user opens the menu and chooses `Start KA Lite`
   - first message appears: `Starting...`
   - then `Stopped` appears, but the icon is representing the running state and
   - no `You can now open the browser...` message 

2. Server is running  - user opens the menu and chooses `Stop KA Lite`
   - first message appears: `Stopping...`
   - then `You can now open the browser...`
   - finally the `Stopped` appears

## Branch or installer

0.16 (build 66) on (I think) all versions of OSX. 

## Screenshots

This would require captured video, do you have any Mac app suggestion for that  @cpauya?

### PR DESCRIPTION
**Pull request by cpauya**
**Update:** Fri, 4 Mar 2016

This PR now does the following:

* fixes #358
* fixes #370
* addresses #349 

---

Hi @aronasorman - still a WIP which eventually fixes #358

(text copied from issue filed #358)

I modified the OS X installer's post install script to replace the `kalite manage init_content_items --overwrite` with `kalite retrievecontentpack local en path-to-en.zip` -- then built the .pkg, installed on a VM, and noticed that the `~/.kalite/content_databases/content_khan_en.sqlite` on a target VM still has zero bytes.  

I replaced it with the [content.db from Pantry](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/content.db), it's about 12MB+, restarted kalite, but the sidebar didn't display anything.

**What works**

When I ran `kalite manage retrievecontentpack local en path-to-en.zip` in the target VM - it works!  The `content_khan_en.sqlite` now has 81MB+ in size.

Running the same .pkg on the target VM twice works too and it also generates the same size.

**Questions**

1. Any idea why the diff in size between the local .sqlite generated with `retrievecontentpack` versus the one in Pantry's is so big?
2. There is no tree of videos to download at Manage - Videos tab.

Setup of build:

* used `ka-lite/0.16.x` branch
* used `installers/develop` branch
* build script now includes the [contentpacks/en.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip) along with the [assessment.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/khan_assessment.zip) when building the .pkg

On the side, the `KA-Lite.pkg` is now 691MB+ (with contentpacks/en.zip and assessment.zip) and will require at least 1.3GB+ when installed on a target Mac OS X machine.

### CODE REVIEW

**Comment by cpauya** [comment]
Thanks @aronasorman - the updated `content.db` you uploaded now works.  So I used it and comment-out the use of the `retrievecontentpacks`.  The `KA-Lite.pkg` is now lower at 405MB+ and requires 817MB+ to install.

However, I have these issues when I replaced the .sqlite with the new `content.db` and navigated KA-Lite as installed in a VM:

1. On the exercise page

    > [Error] SyntaxError: JSON Parse error: Unexpected identifier "undefined"
    parse (bundle_common.js, line 55)
    get_item_data (bundle_common.js, line 55)
    ...
    n (bundle_common.js, line 824)
    (anonymous function) (bundle_common.js, line 824)

1. On the Video download page, the video tree doesn't load and here's the only Console error:

    > [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (loading.gif, line 0)

1. And on the sidebar, I can't see the unavailable items like video, I'd think that is a feature? :smile_cat:

Any ideas where I should look?

**Comment by aronasorman** [comment]
> On the side, the KA-Lite.pkg is now 691MB+ (with contentpacks/en.zip and assessment.zip) and will require at least 1.3GB+ when installed on a target Mac OS X machine.

Use either, not both. So if you're using `retrievecontentpack`, then you can drop the assessment zip.

**Comment by aronasorman** [comment]
> On the exercise page

Is this the 0.16.x branch? Once this is merged: https://github.com/learningequality/ka-lite/pull/4827

Hopefully it can fix that error.

**Comment by cpauya** [comment]
Yup it's on the `ka-lite/0.16.x` branch.  

For now, I will use the `content.db` from Pantry and keep the `assessment.zip`.

**Comment by cpauya** [comment]
Tested the latest `ka-lite/0.16.x` and now the exercise page is working for Mavericks, Yosemite, and El Capitan, yey!  

Setup of build:

* used `ka-lite/0.16.x` branch
* used `installers/develop` branch
* build script only uses the [content.db/en.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/content.db) and the [assessment.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/khan_assessment.zip) when building the .pkg

From initial tests, only the video downloads page issue remains with this Console error:

> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (http://127.0.0.1:8008/node_modules/jquery.fancytree/dist/skin-lion/loading.gif, line 0)

**Comment by cpauya** [comment]
Hi @aronasorman - I removed the `assessment.zip` and this now only uses `contentpacks/en.zip` with the `retrievecontentpack` command.

Setup of build:

* used `ka-lite/0.16.x` branch
* this branch based on `installers/develop` branch
* build script only uses the [contentpacks/en.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip) when building the .pkg

From initial tests, only the video downloads page issue remains with this Console error:

> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (http://127.0.0.1:8008/node_modules/jquery.fancytree/dist/skin-lion/loading.gif, line 0)

Any idea why the videos tree is not loading?

**Comment by cpauya** [comment]
Updates:

* the video download page now works
* we now put all "shared" files on the `/Applications/KA-Lite/support/` folder
* updated the OS X installer documentation (readme, release notes, license) and now uses only "Learning Equality" for copyright.

ToDo:

* The images on the exercise page are missing (see screenshot).

screenshot 2016-02-25 19 10 47

/cc: @aronasorman

**Comment by cpauya** [comment]
Hi @radinamatic - the last commit fixed the missing images as per my tests.  

Can you verify that it indeed fixed it based on http://dungeon.learningequality.org:8085/browse/KL-MT16-67/artifact then I can merge this PR.

**Comment by cpauya** [comment]
Latest commit also fixes #370 

@radinamatic If successful, please use the Bamboo build at http://dungeon.learningequality.org:8085/browse/KL-MT16-68KL-MT16-68 for your tests.

**Comment by cpauya** [comment]
Hi @radinamatic - The [build 71 on Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-71/artifact) should contain the fixes for #370 - specifically the missing notifications.

**Comment by radinamatic** [comment]
:+1: @cpauya, downloading!

**Comment by radinamatic** [comment]
@cpauya, I tested build 74 on El Capitan, and I couldn't see the "unreliable" notifications anymore, but that version of OSX is one-big-PITA of a resource hogger, and screenshare actions lag behind my mouse clicks so much that I can't really assess if the display of the notifications is correct.  

Couldn't test at all on Mavericks, see all the details in [#4964](https://github.com/learningequality/ka-lite/issues/4964).

**Comment by cpauya** [comment]
@radinamatic Yup, using El Capitan on a VM sucks - I gave it 2GB of RAM and it wants some more.

Fixes on this PR is already piling-up, and testing them will be harder.  

I think we should merge this now so I can make a build that will include the other fixes like https://github.com/learningequality/ka-lite/issues/4961#issuecomment-192047315.  Is that okay?

**Comment by radinamatic** [comment]
That sounds like a plan for me, but I'd also prefer if @aronasorman gave the "go/no go" order for the merge... :wink:

**Comment by cpauya** [comment]
That's my preference too, I don't want to merge my own PR as much as I want, unless there's no one else to do it.  

Any comments @aronasorman? :smile_cat:

**Comment by aronasorman** [comment]
Go merge!

**Pull request merged**
